DEF_ERROR(ERR_NONE,                 "OK"),
DEF_ERROR(ERR_GENERIC,              "Unknown Error"),
DEF_ERROR(ERR_SEM_CREATE_FAILED,    "Creating semaphore failed"),
DEF_ERROR(ERR_THREAD_CREATE_FAILED, "Creating thread failed"),
DEF_ERROR(ERR_PROCESS_FAILED,       "Creating/Getting process failed"),
DEF_ERROR(ERR_IF_RESET,             "Interface has reset"),
DEF_ERROR(ERR_IF_ALREADY_EXIST,     "Trying to setup an interface already existing"),
DEF_ERROR(ERR_IF_SETUP_FAILED,      "Interface setup failed"),
DEF_ERROR(ERR_IF_CONN_FAILED,       "Connecting to interface failed"),
DEF_ERROR(ERR_IF_REQUEST_FAILED,    "Requesting interface failed"),
DEF_ERROR(ERR_FILE_IO,              "File input/output error"),
DEF_ERROR(ERR_PATH_NOT_EXIST,       "File path does not exist"),
DEF_ERROR(ERR_PATH_ALREADY_EXIST,   "File path already exists"),
DEF_ERROR(ERR_NOT_AVAIL_ON_FILE,    "The desired operation can not be done on files"),
DEF_ERROR(ERR_NOT_AVAIL_ON_DIR,     "The desired operation can not be done on directories"),
DEF_ERROR(ERR_NOT_AVAIL_ON_SUB_DIR, "The desired operation can not be done on sub-directories"),
DEF_ERROR(ERR_NOT_AVAIL_ON_ROOT_DIR,"The desired operation can not be done on root directories"),
DEF_ERROR(ERR_OPEN_FILE_FAILED,     "Open file failed"),
DEF_ERROR(ERR_CREATE_FILE_FAILED,   "Create file failed"),
DEF_ERROR(ERR_CREATE_DIR_FAILED,    "Create directory failed"),
DEF_ERROR(ERR_LOAD_LIBRARY_FAILED,  "Load dynamic linked library failed"),
DEF_ERROR(ERR_BAD_CONFIG_FORMAT,    "Bad config file format"),
DEF_ERROR(ERR_BUFFER_OVERFLOW,      "Buffer overflow"),
DEF_ERROR(ERR_EXEC_NOT_FOUND,       "Executable not found"),
DEF_ERROR(ERR_EXEC_INFO_NOT_FOUND,  "Executable information not found"),
DEF_ERROR(ERR_EXEC_INFO_NOT_VALID,  "Executable information not valid"),
DEF_ERROR(ERR_CUR_DIR_NOT_FOUND,    "Current directory not found"),
DEF_ERROR(ERR_INVALID_PATH,         "File path not valid"),
DEF_ERROR(ERR_DUP_PROCESS,          "Process already exists"),
DEF_ERROR(ERR_INVALID_TYPE,         "Invalid config value type"),
DEF_ERROR(ERR_INSUFFICIENT_BUFSIZE, "Buffer size is not enough"),
DEF_ERROR(ERR_BUSY,                 "System is busy"),
DEF_ERROR(ERR_TIMEOUT,              "Timeout"),
DEF_ERROR(ERR_MODULE_NOT_FOUND,     "The desired module is not found"),
DEF_ERROR(ERR_MODULE_NOT_INITED,    "The module is not initiated"),
DEF_ERROR(ERR_INVALID_PARAM,        "Invalid calling parameters"),
DEF_ERROR(ERR_INVALID_CMD,          "Invalid command"),
DEF_ERROR(ERR_INVALID_MPATTERN,     "Invalid match pattern"),
DEF_ERROR(ERR_INVALID_ENV_NAME,     "Invalid environment variable name"),
DEF_ERROR(ERR_PARSE_ENV_FAILED,     "Error occurred while replacing environment variables"),
DEF_ERROR(ERR_ENV_NOT_FOUND,        "The desired environment variable is not found"),
DEF_ERROR(ERR_FS_NO_ACCESS,         "The desired FS system access is denied"),
DEF_ERROR(ERR_FS_INVALID_HANDLE,    "FS handle invalid"),
DEF_ERROR(ERR_FS_NEGATIVE_POSITION, "Trying to set a file pointer to a negative value"),
DEF_ERROR(ERR_FS_DEV_NOT_FOUND,     "File system device not found"),
DEF_ERROR(ERR_FS_DEV_MOUNT_FAILED,  "File system device mount failed"),
DEF_ERROR(ERR_FS_DEV_FORMAT_FAILED, "File system device format failed"),
DEF_ERROR(ERR_FS_DEV_MOUNT_FAILED_NOT_EXIST,          "File system device mount failed due to device not existing"),
DEF_ERROR(ERR_FS_DEV_MOUNT_FAILED_ALREADY_MOUNTED,    "File system device mount failed due to device already mounted"),
DEF_ERROR(ERR_FS_DEV_FORMAT_FAILED_ALREADY_INUSE,     "File system device format failed due to device already in-use"),
DEF_ERROR(ERR_FS_FILE_DIR_LOCKED,   "File or directory is locked (probably in use)"),
